### ISSUE TITLE
Corp logo's

### ISSUE THREAD

**Issue by draymah** [dimurgos/Slack-Eve-Killmail#10]
Is there a way to add the corp logos to the template ?

**Comment by draymah** [comment]
Or at least add the corp name after the Player

**Comment by dimurgos** [comment]
So something like this: 
![proposal](https://cloud.githubusercontent.com/assets/936948/25772087/1c77f3ae-3263-11e7-906b-9559c243ca7b.png)

**Comment by dimurgos** [comment]
Even though question would be, which corp logo would be added. The attacker isn't necessarily from the corp you are listing in killmail. So I imagine it wouldn't make the killer corp obviously instantly. So it depends on what you want.

**Comment by dimurgos** [comment]
Managed to make this: 
![proposal_2](https://cloud.githubusercontent.com/assets/936948/25773030/8f526da6-3276-11e7-8877-57283c6c8ed9.png)

Shows the top 10 attackers from your alliance or corporation with the victim corp image on top and the corp that did the kill on the side of the attacker. In case of a death it will not show a list of attackers (unless you got killed by somebody in your own corp).

**Comment by draymah** [comment]
the first one you listed ,but maybe showing 

Pilot (Corp)(Alliance) was killed by Pilot (Corp)(Alliance) would be pretty good as well,

**Comment by dimurgos** [comment]
Added a config setting 'config_extended_name' for showing the corp and alliance (alliance only for the right side as I imagine otherwise it will be a too long text).

![proposal](https://cloud.githubusercontent.com/assets/936948/25779573/44e05c14-331c-11e7-822b-a50d2d1b33e6.png)

**Comment by draymah** [comment]
Great, didn't expect such a fast response :)

**Comment by draymah** [comment]
Just testing on a windows box, getting this error

![image](https://cloud.githubusercontent.com/assets/16655320/25780000/15a9b632-3364-11e7-9763-80e07ded91c4.png)

**Comment by dimurgos** [comment]
Right my bad, fixed in latest push
