### ISSUE TITLE
KeyError while running the killboard.py

### ISSUE THREAD

**Issue by lemonpie23** [dimurgos/Slack-Eve-Killmail#11]
I've set everything in the config as you suggest but when i manually run the killboard.py the only outcome is:

`
KeyError in processing record: 'killID'
KeyError in processing record: 'killID'
KeyError in processing record: 'killID'
KeyError in processing record: 'killID'
`
Any ideas?

**Comment by dimurgos** [comment]
Awesome, apparently they changed the API. Will have to make a few changes.

**Comment by dimurgos** [comment]
Pushed a new change. Should work but would appreciate you trying it out :)

**Comment by lemonpie23** [comment]
@dimurgos Thank you for trying, unfortunately same error again (i did clone again).

*correction. Error changed to `kill_id` of course

**Comment by dimurgos** [comment]
Whoops my bad, should have been killmail_id. The only entry that changed completely.

Try again please :)

**Comment by lemonpie23** [comment]
`KeyError in processing record: 'character_name'`
On to another thing :P 

I tried to edit this out from the killboard.py and the outcome now is:
`KeyError in processing record: 'corporationID'`

Figured you should know about it :D

**Comment by dimurgos** [comment]
And ofcourse they dropped support for names all together. So Ill have to use a different API for character/alliance/corporation naming which will take slightly longer. Ill see if I can fix it later today. Sorry for the inconvenience.

**Comment by lemonpie23** [comment]
Don't worry about it. I'm happy that you are still working on this one :D 
Good luck!

**Comment by dimurgos** [comment]
Right I think I got it sorted now. Also changed to the new CCP ESI API as I found out the API I am using for ship types is deprecated. As far as I can see it works as expected again.

**Comment by lemonpie23** [comment]
Yep. It does work as expected on slack. Thank you!
A small note for you, it doesn't work on discord if you use {discord_url/slack} in the config(other tools work like that). `HTTPError in processing record: Forbidden`
I don't expect an implementation for discord but i would appreciate it if you knew a way i could do it off the top of your head.
Nevertheless you fixed it and i'm happy about it. Thanks again.

**Comment by dimurgos** [comment]
Well the forbidden says that credentials aren't properly given. I imagine this may be something related to the way discord wants credentials or identity given. It's difficult to guess what causes the specific issue. I'd have to dive into discord to see how the webhook functions. 

I do see one thing you could try:

on line 153 on killboard.py change the 'payload' to 'payload_json'

**Comment by dimurgos** [comment]
If you do change it can't be used for slack ;) but if it works, Id be able to make a configuration about it.

**Comment by lemonpie23** [comment]
No luck so far. If i ever find a way i will let you know. 
Anyway, your program works as intended, so thank you for your time and effort 👍

**Comment by dimurgos** [comment]
Got it working for discord, pushing change.

**Comment by lemonpie23** [comment]
@dimurgos You are amazing! if you provide an ingame name i can send you some love :)
Thanks 👍 

Edit:

I know i have bothered you enough already but here are some other things i've noticed you might be interested in.

- I can't make the program run at start up using your script, (something wrong with the script or missing instructions?)
- Config > line 9 `If True, properly posts for discord` this is misleading, in order to work properly with discord you need to enter `discord_webhook_url/slack` not just the url.
- At this point i demand a way to send you some isk :)
Thank you!

**Comment by dimurgos** [comment]
Improved instructions a bit. Also I sadly don't play anymore, so it's fine :)

**Comment by lemonpie23** [comment]
i'm sorry to hear that. anyway. Thanks o7
