### ISSUE TITLE
Any way to make it not post kills below a certain value?

### ISSUE THREAD

**Issue by ficti0n1** [dimurgos/Slack-Eve-Killmail#17]
For example 5mil?

Great bot though, thanks for your work.

**Comment by dimurgos** [comment]
Added the value check to a branch. You can test it if you want :). 

https://github.com/dimurgos/Slack-Eve-Killmail/tree/minimum-value

**Comment by ficti0n1** [comment]
It appears to be posting all kills BELOW that value rather then ABOVE.

Again many thanks for developing this tool for a game which you said you don't play anymore.

**Comment by dimurgos** [comment]
Sorry about that. Pushed an update that should fix that. Thanks for testing!
