### ISSUE TITLE
Error in processing record

### ISSUE THREAD

**Issue by ficti0n1** [dimurgos/Slack-Eve-Killmail#18]
![image](https://user-images.githubusercontent.com/36131270/38778153-af13fd54-40ac-11e8-9c0b-732987e626b2.png)

Many kills not processing with the above error. Has this been encountered by anyone else?

**Comment by dimurgos** [comment]
Thanks for the report. Found the issue, newest commit should fix it.

**Comment by ficti0n1** [comment]
Sadly now I am getting a character_id error:

![image](https://user-images.githubusercontent.com/36131270/38800748-f437021a-415f-11e8-86d2-9bc53661cc0c.png)

**Comment by dimurgos** [comment]
Right so apparently an attacker can both have no character_id and not be part of a faction. Should be fixed now.

**Comment by ficti0n1** [comment]
Wow that's quick :)

Yes for example structures can have none. Seems to be working now.

**Comment by dimurgos** [comment]
Quick because I was about 95% sure it would be a probable issue (so I guess I should have properly fixed it the first time around 😛 ). Anyways, glad it works now.
