### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by ghost** [dimurgos/Slack-Eve-Killmail#2]
I'm getting the following error when I try to run it:

`Exception in processing record<class 'locale.Error'>`

**Comment by dimurgos** [comment]
I imagine thats related to me using LC_ALL 'en_US' locale for showing the ISK values. So I guess you don't have that installed. Two options would be to actually install en_US locale or, change the line with locale.setlocale(locale.LC_ALL,'en_US') to a locale you actually have.

Not sure which system you run, in Ubuntu you should be able to fix this using:

sudo apt-get install language-pack-en-base
sudo dpkg-reconfigure locales

**Comment by dimurgos** [comment]
Added configuration options in config.py and added example for when running windows

**Comment by ghost** [comment]
> Setting up language-pack-en (1:14.04+20150219) ...
> Setting up language-pack-en-base (1:14.04+20150219) ...
> Generating locales...
>   en_AG.UTF-8... done
>   en_AU.UTF-8... done
>   en_BW.UTF-8... done
>   en_CA.UTF-8... done
>   en_DK.UTF-8... done
>   en_GB.UTF-8... done
>   en_HK.UTF-8... done
>   en_IE.UTF-8... done
>   en_IN.UTF-8... done
>   en_NG.UTF-8... done
>   en_NZ.UTF-8... done
>   en_PH.UTF-8... done
>   en_SG.UTF-8... done
>   en_US.UTF-8... up-to-date
>   en_ZA.UTF-8... done
>   en_ZM.UTF-8... done
>   en_ZW.UTF-8... done
> Generation complete.
> raikia@sunburst:~/slack_killmail/Slack-Eve-Killmail$ sudo dpkg-reconfigure locales
> Generating locales...
>   en_AG.UTF-8... up-to-date
>   en_AU.UTF-8... up-to-date
>   en_BW.UTF-8... up-to-date
>   en_CA.UTF-8... up-to-date
>   en_DK.UTF-8... up-to-date
>   en_GB.UTF-8... up-to-date
>   en_HK.UTF-8... up-to-date
>   en_IE.UTF-8... up-to-date
>   en_IN.UTF-8... up-to-date
>   en_NG.UTF-8... up-to-date
>   en_NZ.UTF-8... up-to-date
>   en_PH.UTF-8... up-to-date
>   en_SG.UTF-8... up-to-date
>   en_US.UTF-8... up-to-date
>   en_ZA.UTF-8... up-to-date
>   en_ZM.UTF-8... up-to-date
>   en_ZW.UTF-8... up-to-date
> Generation complete.
> raikia@sunburst:~/slack_killmail/Slack-Eve-Killmail$ python killboard.py
> Exception in processing record<class 'locale.Error'>
> ^CTraceback (most recent call last):
>   File "killboard.py", line 137, in <module>
>     time.sleep(60)
> KeyboardInterrupt
> raikia@sunburst:~/slack_killmail/Slack-Eve-Killmail$

Hmm...still gets the locale.Error :-/.  I'm on Ubuntu 14.04

**Comment by dimurgos** [comment]
If you have the latest version, change the following line in config.py: 

config_locale = 'en_US' # Linux locale

to:

config_locale = 'en_US.UTF-8'

If you don't have the latest version, change the line:

```
locale.setlocale(locale.LC_ALL, 'en_US')
```

to 

```
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
```

**Comment by ghost** [comment]
Ah, it worked!  Thanks!  Great script!
