### ISSUE TITLE
A little issue I can't resolve.

### ISSUE THREAD

**Issue by Willhelmm** [dimurgos/Slack-Eve-Killmail#3]
Hi, I'm a having a little error 
"Exception in processing record: '987194902' (Example corp ID)"

I don't know how to fix this. Thanks

**Comment by dimurgos** [comment]
It's really important that you configure the example corp in config.py like: 

config_owner = [{'corporationID': 987194902}]

If it's actually an alliance, it has to be:

config_owner = [{'allianceID': 987194902}]

The id has to actually be on zkillboard to work (so https://zkillboard.com/corporation/987194902/ has to work (which it doesn't, so either wrong id by accident or you just wanted to give an example)).

**Comment by Willhelmm** [comment]
Works perfectly, thanks!
