### ISSUE TITLE
Multiple alliance / corporation ID example?

### ISSUE THREAD

**Issue by phneak** [dimurgos/Slack-Eve-Killmail#5]
I am trying to get multiple alliance / corporation IDs working.  Here is what I have configured but it does not appear to be working?

config_owner = [{'allianceID': 99006113, 'allianceID': 99005065, 'allianceID': 99004364, 'corporationID': 98290394, 'corporationID': 98360068}]

**Comment by Parkham** [comment]
Make sure you're putting one space before and after colons.  Like this:

config_owner = [{'allianceID' : 99006113, 'allianceID' : 99005065,

**Comment by dimurgos** [comment]
Its actually [{'allianceID': 99006113}, {'allianceID': 99005065}, {'allianceID': 99004364}, {'corporationID': 98290394}, {'corporationID': 98360068}]

Sorry for my late reply.
