### ISSUE TITLE
urllib error

### ISSUE THREAD

**Issue by Parkham** [dimurgos/Slack-Eve-Killmail#7]
Started getting the following error on 20MAY2016 1252 GMT:

<class 'urllib2.URLError'> (urlopen error {Errno 110} Connection timed out>)

I'm not sure which url is causing the issue.

**Comment by dimurgos** [comment]
They changed the URL for the public crest. Ill push a patch which should work. Sadly not in the position to test anymore. The new URL is https://crest-tq.eveonline.com/ and it is part of the util.py.

**Comment by Parkham** [comment]
Testing it now, will let you know.  Thanks,dude.

**Comment by Parkham** [comment]
It's working.  Our Slack channel is blowing up now with killmails

**Comment by dimurgos** [comment]
Thanks for testing :)

**Comment by Parkham** [comment]
Any idea why we're now getting:
 HTTPError in processing record: NOT FOUND

**Comment by dimurgos** [comment]
Do you get it constantly? Or only once in a while? I have the feeling one of the kills being reported by zkillboard is referring to a wrong ship, constellation or region. But that can only be the case if it happens once, otherwise they changed some part of the API. Only way for me to tell which one is by going through the kill list that you are reporting from.

You can also do that yourself btw, go to https://zkillboard.com/api/[corporation]/[id]/

From that I use the solarSystemID for https://crest-tq.eveonline.com/solarsystems/[solarSystemId]/ and continuing through the paths, and, the shipTypeID through the https://crest-tq.eveonline.com/types/[shipTypeID]/ . The reason why I think it's something related to the EVE api is that the NOT FOUND spelling is not that common to report 404, but, crest-tq seems to reports it like that.

**Comment by Parkham** [comment]
Right after it launchers, it repeats over and over - no kills post

**Comment by Parkham** [comment]
So, should I just let it run and maybe it'll work itself out?
The last reported kill was on 15JUN2016 2:48 eve time

**Comment by dimurgos** [comment]
I think I found it, give me a sec I'll push a change, see if that works better

**Comment by dimurgos** [comment]
Or you can try it yourself: in the ships.py, change     root = util.get_public_crest_data('types', id) to     root = util.get_public_crest_data('inventory/types', id)

So the 'types' to 'inventory/types', apparently they changed the path

**Comment by Parkham** [comment]
GEtting KeyError in processing record: 'inventory/types'

**Comment by dimurgos** [comment]
Ok ty :) pushed a change. Added new util method that appends the inventory to the URL.

**Comment by Parkham** [comment]
where are you getting the change information so quick?  I would like to help as well

**Comment by dimurgos** [comment]
Well based on the error it was likely to be a crest error. If it continiously happens it's a global error instead of a local missing type. So I just ran through the possibilities. But I used the type URL for versioning too so I can't change it that quickly. Going to fix it better in a sec though. But I would like to know if it works with latest push :).

**Comment by Parkham** [comment]
Generic exception in processing record: <type 'exceptions.AttributeError'>

**Comment by Parkham** [comment]
only change was ship.py right?

**Comment by dimurgos** [comment]
No added something in util.py too.

**Comment by Parkham** [comment]
oh wait..just saw it  sorry one sec

**Comment by Parkham** [comment]
do you have a direct link so I wget

**Comment by dimurgos** [comment]
https://github.com/dimurgos/Slack-Eve-Killmail/blob/master/util.py

**Comment by dimurgos** [comment]
Going to push a new change, the first change with the inventory/types actually did work (I think anyways) but I had to change something in version.py.

**Comment by Parkham** [comment]
I figured I did something wrong.  I can't copy paste unfortunately

**Comment by dimurgos** [comment]
So basically, from the original 'solution' to change to root = util.get_public_crest_data('inventory/types', id), you will have to change the version.py as well to set     'types': 'ItemType-v3' to   'inventory/types': 'ItemType-v3'

so that would only require a change in ships.py and version.py

**Comment by Parkham** [comment]
still getting errors.. will need to check all the changes..might take a while.  sorry

I couldn't wget the file

**Comment by dimurgos** [comment]
What error are you getting? 

I am sorry about not being able to give you a simple/quick answer (or fix it instantly without issues), I don't have any way to test anymore.

**Comment by Parkham** [comment]
Generic exception in processing record: has no attribute get_public_crest_data

**Comment by dimurgos** [comment]
Ah that sounds like something went wrong in merging.

util.py should look like this:

```
import urllib2
import urllib
import json
import config
import version

def get_public_crest_data(type, id):
    request = urllib2.Request('https://crest-tq.eveonline.com/{0}/{1}/'.format(type, id))
    request.add_header('User-Agent', config.config_header)
    request.add_header('Accept', 'application/vnd.ccp.eve.{0}+json;charset=utf-8'.format(version.api_versions[type]))
    opener = urllib2.build_opener()
    data = opener.open(request)
    return json.load(data)

def get_public_crest_data_href(type, href):
    request = urllib2.Request(href)
    request.add_header('User-Agent', config.config_header)
    request.add_header('Accept', 'application/vnd.ccp.eve.{0}+json;charset=utf-8'.format(version.api_versions[type]))
    opener = urllib2.build_opener()
    data = opener.open(request)
    return json.load(data)
```

ships.py should look like this:

```
import util

ship_list = {}

def get_ship_by_id(id):
    if id in ship_list:
        return ship_list[id]

    root = util.get_public_crest_data('inventory/types', id)

    typeName = root['name']
    ship_list[id] = typeName
    return typeName
```

**Comment by Parkham** [comment]
OK, I changed it back.. testing

**Comment by Parkham** [comment]
bam, working.  thanks a bazillion.  If there's any way I can help in future, let me know

**Comment by dimurgos** [comment]
Cheers :) happy it works. And well, if you are active on forums on eve and if you ever notice posts in the development area with names like 'Devsite Blog: CREST Renovations for June 2016', I would appreciate the heads up. Apparently CCP likes to change API paths suddenly (bad practice but I imagine they have their reasons).

And, if you ever run in any problems, I am just a bug report away ;)
