### ISSUE TITLE
Unable to deamonize, can you cron?

### ISSUE THREAD

**Issue by IronWarjack** [dimurgos/Slack-Eve-Killmail#8]
Love the script, works perfect, but I am unable to run as a daemon.  (I do not have rights to do so on system) When I puTTY in and run it command, it's great, until the window must be closed.

Can you also run this as a cron job, and if so, anything special to change in config?

**Comment by dimurgos** [comment]
With the current code you can't run it in cron, as it is intended to run as a daemon. You would have to remove the 'while True:'. That way it will run once, and you would be able to run the application at a scheduled moment.

If you can't run it as a daemon you can do the following:

`python killboard.py &`

This will launch a local daemon and return you the PID which you need to 'cleanly' kill it. 

A quick launch script would look something like:

#!/bin/bash

if [ -a run.pid ]
then
        value=`cat run.pid`
        kill $value
fi
python killboard.py 1>&2 >> run.log &
echo $! > run.pid

**Comment by IronWarjack** [comment]
I was able to set it up as a cron and kill the deamon as mentioned.

With sadness, the alliance I work with has far more red than green to deal with.  So while it has been posting every 20 as expected (all red).  The first green to pass by since getting this working on 7/30, occurred recently and did not get posted... not sure if I messed something up on my "adjustments".

**Comment by IronWarjack** [comment]
So, the short answer is, the original issue is resolved.  It's working as a cron.  Perhaps with a few glitches, but I may be able to resolve them with some work once I figure out what I may have done.

**Comment by dimurgos** [comment]
Well there could be two things. If you changed it to a cronjob (so by removing the 'keep running' behaviour with the while True:) it could be a matter of timing, for example, the cronjob is scheduled slightly before the last post and so it will be posted in next run, or, the kill occurred before the 'config_check' time (default at 24h). The config_check is the recent time of kills (to lighten the load for zkillboard).

**Comment by IronWarjack** [comment]
You were dead on, the second run just happened and there was the green...
the one, lonely, green.

Thanks, wonderful web integration!
