### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MMGIFL** [dimurgos/Slack-Eve-Killmail#9]
Is it possible to use this without hosting your own killboard?

**Comment by dimurgos** [comment]
That depends on what you mean. The tool retrieves the kills from zkillboard.com, so you would need to have your corp registered there to get all the kills. It then posts on slack.com, on your own slack channel. So those two parts are not hosted 'by yourself'.

I imagine what you mean is if this tool can be run by a third party so you don't have to run it yourself. This is possible but I imagine it will require some front end tooling and interest by at least a few people to make it worth the effort. 

You could btw launch an AWS instance, which is free if you keep below certain thresholds, which should be fine as it won't take much to keep this tool running.

**Comment by MMGIFL** [comment]
@dimurgos  i meant zkillboard self hosted, so the first part answered my question thank you so much going to give this a go now

**Comment by dimurgos** [comment]
Cheers :)
